export async function GET() {
  return Response.json({
    data: [
      {
        id: 1,
        name: "Emily Carter",
        submitted: "03/15/2024 10:30AM",
        status: "Reached Out",
        country: "United States",
      },
      {
        id: 2,
        name: "Liam O'Connor",
        submitted: "03/14/2024 4:15PM",
        status: "Pending",
        country: "Ireland",
      },
      {
        id: 3,
        name: "Sophia Kim",
        submitted: "03/13/2024 9:00AM",
        status: "Reached Out",
        country: "South Korea",
      },
      {
        id: 4,
        name: "Mohammed Ali",
        submitted: "03/12/2024 1:45PM",
        status: "Pending",
        country: "Egypt",
      },
      {
        id: 5,
        name: "Isabella Rossi",
        submitted: "03/11/2024 11:20AM",
        status: "Reached Out",
        country: "Italy",
      },
      {
        id: 6,
        name: "Noah Tanaka",
        submitted: "03/10/2024 3:55PM",
        status: "Pending",
        country: "Japan",
      },
      {
        id: 7,
        name: "Emma Müller",
        submitted: "03/09/2024 8:10AM",
        status: "Reached Out",
        country: "Germany",
      },
      {
        id: 8,
        name: "Lucas Silva",
        submitted: "03/08/2024 2:30PM",
        status: "Pending",
        country: "Brazil",
      },
      {
        id: 9,
        name: "Ava Johnson",
        submitted: "03/07/2024 7:45AM",
        status: "Reached Out",
        country: "Canada",
      },
      {
        id: 10,
        name: "Oliver Smith",
        submitted: "03/06/2024 5:00PM",
        status: "Pending",
        country: "Australia",
      },
      {
        id: 11,
        name: "Mia González",
        submitted: "03/05/2024 12:15PM",
        status: "Reached Out",
        country: "Spain",
      },
      {
        id: 12,
        name: "Ethan Brown",
        submitted: "03/04/2024 6:40AM",
        status: "Pending",
        country: "United Kingdom",
      },
      {
        id: 13,
        name: "Charlotte Lee",
        submitted: "03/03/2024 3:25PM",
        status: "Reached Out",
        country: "Singapore",
      },
      {
        id: 14,
        name: "James Wilson",
        submitted: "03/02/2024 10:50AM",
        status: "Pending",
        country: "New Zealand",
      },
      {
        id: 15,
        name: "Amelia Garcia",
        submitted: "03/01/2024 2:05PM",
        status: "Reached Out",
        country: "Mexico",
      },
      {
        id: 16,
        name: "Benjamin Martinez",
        submitted: "02/29/2024 9:15AM",
        status: "Pending",
        country: "Argentina",
      },
      {
        id: 17,
        name: "Evelyn Lopez",
        submitted: "02/28/2024 4:40PM",
        status: "Reached Out",
        country: "Colombia",
      },
      {
        id: 18,
        name: "William Hernandez",
        submitted: "02/27/2024 11:55AM",
        status: "Pending",
        country: "Chile",
      },
      {
        id: 19,
        name: "Mila Rodriguez",
        submitted: "02/26/2024 7:30AM",
        status: "Reached Out",
        country: "Peru",
      },
      {
        id: 20,
        name: "Henry Gonzalez",
        submitted: "02/25/2024 1:20PM",
        status: "Pending",
        country: "Venezuela",
      },
      {
        id: 21,
        name: "Luna Perez",
        submitted: "02/24/2024 8:45AM",
        status: "Reached Out",
        country: "Ecuador",
      },
      {
        id: 22,
        name: "Alexander Torres",
        submitted: "02/23/2024 5:10PM",
        status: "Pending",
        country: "Costa Rica",
      },
      {
        id: 23,
        name: "Ella Flores",
        submitted: "02/22/2024 12:35PM",
        status: "Reached Out",
        country: "Panama",
      },
      {
        id: 24,
        name: "Daniel Ramirez",
        submitted: "02/21/2024 9:50AM",
        status: "Pending",
        country: "Uruguay",
      },
      {
        id: 25,
        name: "Grace Morales",
        submitted: "02/20/2024 3:15PM",
        status: "Reached Out",
        country: "Paraguay",
      },
      {
        id: 26,
        name: "Michael Ortiz",
        submitted: "02/19/2024 10:40AM",
        status: "Pending",
        country: "Bolivia",
      },
      {
        id: 27,
        name: "Chloe Rivera",
        submitted: "02/18/2024 6:05PM",
        status: "Reached Out",
        country: "Guatemala",
      },
      {
        id: 28,
        name: "Logan Cruz",
        submitted: "02/17/2024 1:30PM",
        status: "Pending",
        country: "Honduras",
      },
      {
        id: 29,
        name: "Zoe Gomez",
        submitted: "02/16/2024 8:55AM",
        status: "Reached Out",
        country: "El Salvador",
      },
      {
        id: 30,
        name: "Jackson Reyes",
        submitted: "02/15/2024 4:20PM",
        status: "Pending",
        country: "Nicaragua",
      },
      {
        id: 31,
        name: "Lily Diaz",
        submitted: "02/14/2024 11:45AM",
        status: "Reached Out",
        country: "Cuba",
      },
      {
        id: 32,
        name: "Sebastian Vega",
        submitted: "02/13/2024 7:10AM",
        status: "Pending",
        country: "Dominican Republic",
      },
      {
        id: 33,
        name: "Aria Castillo",
        submitted: "02/12/2024 2:35PM",
        status: "Reached Out",
        country: "Puerto Rico",
      },
      {
        id: 34,
        name: "Mateo Alvarez",
        submitted: "02/11/2024 9:00AM",
        status: "Pending",
        country: "Haiti",
      },
      {
        id: 35,
        name: "Scarlett Ruiz",
        submitted: "02/10/2024 5:25PM",
        status: "Reached Out",
        country: "Mexico",
      },
      {
        id: 36,
        name: "David Morales",
        submitted: "02/09/2024 12:50PM",
        status: "Pending",
        country: "Mexico",
      },
      {
        id: 37,
        name: "Victoria Chavez",
        submitted: "02/08/2024 8:15AM",
        status: "Reached Out",
        country: "Mexico",
      },
      {
        id: 38,
        name: "Joseph Herrera",
        submitted: "02/07/2024 3:40PM",
        status: "Pending",
        country: "Mexico",
      },
      {
        id: 39,
        name: "Penelope Jimenez",
        submitted: "02/06/2024 11:05AM",
        status: "Reached Out",
        country: "Mexico",
      },
      {
        id: 40,
        name: "Samuel Ortega",
        submitted: "02/05/2024 6:30AM",
        status: "Pending",
        country: "Mexico",
      },
      {
        id: 41,
        name: "Hannah Vargas",
        submitted: "02/04/2024 1:55PM",
        status: "Reached Out",
        country: "Mexico",
      },
      {
        id: 42,
        name: "Owen Rios",
        submitted: "02/03/2024 9:20AM",
        status: "Pending",
        country: "Mexico",
      },
      {
        id: 43,
        name: "Addison Mendoza",
        submitted: "02/02/2024 4:45PM",
        status: "Reached Out",
        country: "Mexico",
      },
      {
        id: 44,
        name: "Gabriel Aguilar",
        submitted: "02/01/2024 12:10PM",
        status: "Pending",
        country: "Mexico",
      },
      {
        id: 45,
        name: "Natalie Romero",
        submitted: "01/31/2024 7:35AM",
        status: "Reached Out",
        country: "Mexico",
      },
      {
        id: 46,
        name: "Carter Navarro",
        submitted: "01/30/2024 3:00PM",
        status: "Pending",
        country: "Mexico",
      },
      {
        id: 47,
        name: "Eleanor Guzman",
        submitted: "01/29/2024 10:25AM",
        status: "Reached Out",
        country: "Mexico",
      },
      {
        id: 48,
        name: "Luke Pena",
        submitted: "01/28/2024 5:50AM",
        status: "Pending",
        country: "Mexico",
      },
      {
        id: 49,
        name: "Stella Rojas",
        submitted: "01/27/2024 1:15PM",
        status: "Reached Out",
        country: "Mexico",
      },
    ],
  });
}
